### PR TITLE
Compiler warning removed

### PR DESCRIPTION
**Pull request by derick182**
See issue #52 for further details

### CODE REVIEW

**Comment by sahandnayebaziz** [comment]
Thank you taking care of this @derick182 :)

**Comment by sahandnayebaziz** [comment]
@icanzilb any chance to merge this in?

**Comment by sahandnayebaziz** [comment]
hey @icanzilb bumping this because it has been a month! Can you please this merge this in? Easy Animation continues to display 3 warnings in Xcode. 

screen shot 2017-06-08 at 6 50 09 pm

**Comment by icanzilb** [comment]
hey, expecting a baby any moment, but I'll try looking at this

**Comment by sahandnayebaziz** [comment]
AH nice! Congratulations and all the best man ❤️

**Comment by icanzilb** [comment]
this looks good, merging ... Thank you!

**Pull request merged**
