### PR TITLE
Add an xcodeproj for Carthage support

### PR DESCRIPTION
**Pull request by ianyh**
Carthage uses version tags to determine what to checkout, so you'll need to tag `0.7.1` after merging to actually finish adding support. I've updated the `.podspec` version already.

### CODE REVIEW

**Comment by ianyh** [comment]
Updated to support `1.0.0`. The new tag should be `1.0.1`.

**Comment by ianyh** [comment]
This completes #12, FYI.

**Comment by icanzilb** [comment]
Thanks for doing the PR! Merged and pushed. Does carthage support need any instructions in the README to tell people how to install easyanimation ?

**Comment by ianyh** [comment]
Not strictly speaking, no. I can do a PR later to update the README with some relevant information, though.

**Comment by icanzilb** [comment]
cool with me if you feel like it, there's an Installation section towards the bottom and I just metnioned that the repo now supports carthage

**Pull request merged**
